version: '3.8'

services:
  # Agent A - Slack Bot
  slack-agent:
    build: 
      context: ./slack-agent
      dockerfile: Dockerfile
    container_name: manimpro-slack-agent
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - NODE_ENV=development
      - AGENT_B_URL=http://manim-agent:8000
      - DESCOPE_PROJECT_ID=${DESCOPE_PROJECT_ID:-dev-project}
      - DESCOPE_MANAGEMENT_KEY=${DESCOPE_MANAGEMENT_KEY:-dev-key}
      - DEV_JWT_SECRET=manimpro-dev-secret-change-in-production
    depends_on:
      - manim-agent
    restart: unless-stopped
    networks:
      - manimpro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Agent B - Manim Worker
  manim-agent:
    build: 
      context: ./manim-agent
      dockerfile: Dockerfile
    container_name: manimpro-manim-agent
    ports:
      - "8000:8000"
    environment:
      - PYTHON_ENV=development
      - DESCOPE_JWKS_URL=${DESCOPE_JWKS_URL:-https://api.descope.com/v1/keys/dev-project}
      - DEV_JWT_SECRET=manimpro-dev-secret-change-in-production
      - DESCOPE_PROJECT_ID=${DESCOPE_PROJECT_ID:-dev-project}
      - AGENT_B_AUD=manimpro-agent-b
      - MANIM_OUTPUT_DIR=/tmp/manim_output
      - MANIM_CACHE_DIR=/tmp/manim_cache
      - MANIM_QUALITY=medium_quality
      - MANIM_TIMEOUT=120
      - MCP_SERVER_NAME=manimpro-agent-b
      - MCP_VERSION=1.0.0
      - ALLOWED_HOSTS=slack-agent,localhost,127.0.0.1
      - OPENBLAS_NUM_THREADS=1
      - OMP_NUM_THREADS=1
      - DISPLAY=:99
      - MANIMGL_NO_PREVIEW=1
      - MPLBACKEND=Agg
              - MPLCONFIGDIR=/home/manimpro/.matplotlib
      - FONTCONFIG_PATH=/etc/fonts
              - FONTCONFIG_FILE=/etc/fonts/fonts.conf
        - FC_DEBUG=0
        - PANGOCAIRO_BACKEND=fc
        - MANIM_FFMPEG_CODEC_H264=1
    # Remove ulimits - they cause more threading issues than they solve
    networks:
      - manimpro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Optional: Redis for caching (if needed in future)
  redis:
    image: redis:7-alpine
    container_name: manimpro-redis
    ports:
      - "6379:6379"
    networks:
      - manimpro-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  manimpro-network:
    driver: bridge

volumes:
  manim-output:
  manim-cache: 